Shop.Web/Models/ShoppingCart/ShoppingCartIndexModel.cs
namespace Shop.Web.Models.ShoppingCart
{
    public class ShoppingCartIndexModel
    {
        public Shop.Data.Models.ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Shop.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Enums;
using Shop.Data.Models;
using Shop.Web.DataMapper;
using Shop.Web.Models.Order;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrder _orderService;
        private readonly IFood _foodService;
        private readonly ShoppingCart _shoppingCart;
        private readonly Mapper _mapper;
        private static UserManager<ApplicationUser> _userManager;


        public OrderController(IOrder orderService, IFood foodService, ShoppingCart shoppingCart, UserManager<ApplicationUser> userManager)
        {
            _orderService = orderService;
            _shoppingCart = shoppingCart;
            _userManager = userManager;
            _foodService = foodService;
            _mapper = new Mapper();
        }

        public IActionResult Checkout()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some items first");
                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        // [Authorize]
        // [HttpPost]
        // public async Task<IActionResult> Archive(int? page, OrderArchiveModel orderModel)
        // {
        //     ApplicationUser user;
        //     if (!string.IsNullOrEmpty(orderModel.UserId) && User.IsInRole("Admin"))
        //     {
        //         user = await _userManager.FindByIdAsync(orderModel.UserId);
        //     }
        //     else
        //     {
        //         user = await _userManager.GetUserAsync(User);
        //     }

        //     if (!page.HasValue)
        //     {
        //         page = 1;
        //     }

        //     int orderInPage = 5;
        //     int pageCount = (int)Math.Ceiling((double)_orderService.GetAll().Count() / orderInPage);
        //     var orders = _orderService.GetFilteredOrders(user.Id, OrderBy.None, (page.Value - 1) * orderInPage, orderInPage);
        //     var models = _mapper.OrdersToOrderIndexModels(orders);

        //     var model = new OrderArchiveModel
        //     {
        //         Orders = models,
        //         Page = page.Value,
        //         PageCount = pageCount,
        //         UserId = user.Id,
        //     };

        //     return View(model);
        // }

        // [Authorize]
        // // [HttpPost]
        // public async Task<IActionResult> Archive(
        //     int? page = 1, 
        //     string userId="")
        //     // string zipCode = "", 
        //     // string minDate="", 
        //     // string maxDate="",
        //     // decimal? minPrice = null,
        //     // decimal? maxPrice = null,
        //     // OrderBy orderBy = OrderBy.None)
        // {
        //     ApplicationUser user;
        //     if (!string.IsNullOrEmpty(userId) && User.IsInRole("Admin"))
        //     {
        //         user = await _userManager.FindByIdAsync(userId);
        //     }
        //     else
        //     {
        //         user = await _userManager.GetUserAsync(User);
        //     }

        //     if (!page.HasValue)
        //     {
        //         page = 1;
        //     }

        //     int orderInPage = 5;
        //     int pageCount = (int)Math.Ceiling((double)_orderService.GetAll().Count() / orderInPage);
        //     var orders = _orderService.GetFilteredOrders(user.Id, OrderBy.None, (page.Value - 1) * orderInPage, orderInPage);
        //     var models = _mapper.OrdersToOrderIndexModels(orders);

        //     var model = new OrderArchiveModel
        //     {
        //         Orders = models,
        //         Page = page.Value,
        //         PageCount = pageCount,
        //         UserId = user.Id,
        //     };

        //     return View(model);
        // }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderIndexModel model)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some items first");
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var user = await _userManager.FindByIdAsync(userId);

                model.OrderTotal = items.Sum(item => item.Amount * item.Food.Price);
                var order = _mapper.OrderIndexModelToOrder(model, user);

                _orderService.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(model);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order";
            return View();
        }
    }
}

Shop.Web/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Models;
using Shop.Web.Models.ShoppingCart;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IFood _foodService;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IFood foodService, ShoppingCart shoppingCart)
        {
            _foodService = foodService;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Index(bool isValidAmount = true, string returnUrl = "/")
        {
            _shoppingCart.GetShoppingCartItems();

            var model = new ShoppingCartIndexModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
                ReturnUrl = returnUrl
            };

            if (!isValidAmount)
            {
                ViewBag.InvalidAmountText = "*There were not enough items in stock to add*";
            }

            return View("Index", model);
        }

        [HttpGet]
        [Route("/ShoppingCart/Add/{id}/{returnUrl?}")]
        public IActionResult Add(int id, int? amount = 1, string returnUrl=null )
        {
            var food = _foodService.GetById(id);
            returnUrl = returnUrl.Replace("%2F", "/");
            bool isValidAmount = false;
            if (food != null)
            {
                isValidAmount = _shoppingCart.AddToCart(food, amount.Value);
            }

            return Index(isValidAmount, returnUrl);
        }

        public IActionResult Remove(int foodId)
        {
            var food = _foodService.GetById(foodId);
            if (food != null)
            {
                _shoppingCart.RemoveFromCart(food);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Back(string returnUrl="/")
        {
            return Redirect(returnUrl);
        }
    }
}

Shop.Web/Views/ShoppingCart/Index.cshtml
@model Shop.Web.Models.ShoppingCart.ShoppingCartIndexModel
@using System.Globalization

<div class="row checkoutForm" style="margin-bottom:250px;">
    <div style="background-color:rgba(248,248,248,0.6);">
        <h2 >Your shopping cart 
            <br/>Here are the products in your shopping cart.</h2>
    </div>
    <table class="table table-hover table-dark table-stripped table-bordered">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Product</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left"><a class="btn btn-info" asp-controller="Food" asp-action="Index" asp-route-id="@line.Food.Id">@line.Food.Name</a></td>
                    <td class="text-right">@line.Food.Price.ToString("c",CultureInfo.CreateSpecificCulture("en-US"))</td>
                    <td class="text-right">
                        @((line.Amount * line.Food.Price).ToString("c",CultureInfo.CreateSpecificCulture("en-US")))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="Remove" asp-route-foodId="@line.Food.Id"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @(Model.ShoppingCartTotal.ToString("c",CultureInfo.CreateSpecificCulture("en-US")))
                </td>
            </tr>
        </tfoot>
    </table>
    @if(ViewBag.InvalidAmountText != null)
    {
        <div>
            <p class="invalidAmount">@ViewBag.InvalidAmountText</p>
        </div>
    }
    <div>
        <a class="btn btn-back" asp-action="Back" asp-route-returnUrl="@Model.ReturnUrl">Back</a>
    </div>
    @if(Model.ShoppingCart.ShoppingCartItems.Count() != 0)
    {
        <div class="text-right" style="float:right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            </div>
        </div>
    }
    else
    {
        <p>Your cart is empty, add some items to order them</p>
    }
</div>