Shop.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Models;
using Shop.Web.Models.Category;
using Shop.Web.Models.Food;
using System.Linq;
using Shop.Web.DataMapper;

namespace Shop.Web.Controllers
{
	public class CategoryController : Controller
	{
		private readonly ICategory _categoryService;
		private readonly IFood _foodService;
        private readonly Mapper _mapper;

		public CategoryController(ICategory categoryService, IFood foodService)
		{
			_categoryService = categoryService;
			_foodService = foodService;
            _mapper = new Mapper();
		}

		public IActionResult Index()
		{
			var categories = _categoryService.GetAll().
				Select(category => new CategoryListingModel
				{
					Name = category.Name,
					Description = category.Description,
					Id = category.Id,
					ImageUrl = category.ImageUrl
				});

			var model = new CategoryIndexModel
			{
				CategoryList = categories
			};

			return View(model);
		}

		public IActionResult Topic(int id, string searchQuery)
		{
			var category = _categoryService.GetById(id);
			var foods = _foodService.GetFilteredFoods(id, searchQuery);

			var foodListings = foods.Select(food => new FoodListingModel
			{
				Id = food.Id,
				Name = food.Name,
				InStock = food.InStock,
				Price = food.Price,
				ShortDescription = food.ShortDescription,
				Category = _mapper.FoodToCategoryListing(food),
				ImageUrl = food.ImageUrl
			});

			var model = new CategoryTopicModel
			{
				Category = _mapper.CategoryToCategoryListing(category),
				Foods = foodListings
			};

			return View(model);
		}

		public IActionResult Search(int id, string searchQuery)
		{
			return RedirectToAction("Topic", new { id, searchQuery });
		}

		[Authorize(Roles = "Admin")]
		public IActionResult New()
		{
			ViewBag.ActionText = "create";
			ViewBag.Action = "New";
			ViewBag.CancelAction = "Index";
			ViewBag.SubmitText = "Create Category";
			return View("CreateEdit");
		}

		[HttpPost]
		[Authorize(Roles = "Admin")]
		public IActionResult New(CategoryListingModel model)
		{
			if (ModelState.IsValid)
			{
				var category = _mapper.CategoryListingToModel(model);
				_categoryService.NewCategory(category);
				return RedirectToAction("Topic", new { id = category.Id, searchQuery = "" });
			}

			ViewBag.ActionText = "create";
			ViewBag.Action = "New";
			ViewBag.CancelAction = "Index";
			ViewBag.SubmitText = "Create Category";

			return View("CreateEdit", model);
		}

		[Authorize(Roles = "Admin")]
		public IActionResult Edit(int id)
		{
            ViewBag.ActionText = "change";
            ViewBag.Action = "Edit";
            ViewBag.CancelAction = "Topic";
            ViewBag.SubmitText = "Save Changes";
            ViewBag.RouteId=id;

			var category = _categoryService.GetById(id);
			if (category != null)
			{
				var model = _mapper.CategoryToCategoryListing(category);
				return View("CreateEdit" ,model);
			}

			return View("CreateEdit");
		}

		[HttpPost]
		[Authorize(Roles = "Admin")]
		public IActionResult Edit(CategoryListingModel model)
		{
			if (ModelState.IsValid)
			{
				var category = _mapper.CategoryListingToModel(model);
				_categoryService.EditCategory(category);
				return RedirectToAction("Topic", new { id = category.Id, searchQuery = "" });
			}

            ViewBag.ActionText = "change";
            ViewBag.Action = "Edit";
            ViewBag.CancelAction = "Topic";
            ViewBag.SubmitText = "Save Changes";
            ViewBag.RouteId=model.Id;

			return View("CreateEdit",model);
		}

		[Authorize(Roles = "Admin")]
		public IActionResult Delete(int id)
		{
			_categoryService.DeleteCategory(id);

			return RedirectToAction("Index");
		}
	}
}

Shop.Web/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Models;
using Shop.Web.Models.ShoppingCart;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IFood _foodService;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IFood foodService, ShoppingCart shoppingCart)
        {
            _foodService = foodService;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Index(bool isValidAmount = true, string returnUrl = "/")
        {
            _shoppingCart.GetShoppingCartItems();

            var model = new ShoppingCartIndexModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
                ReturnUrl = returnUrl
            };

            if (!isValidAmount)
            {
                ViewBag.InvalidAmountText = "*There were not enough items in stock to add*";
            }

            return View("Index", model);
        }

        [HttpGet]
        [Route("/ShoppingCart/Add/{id}/{returnUrl?}")]
        public IActionResult Add(int id, int? amount = 1, string returnUrl=null )
        {
            var food = _foodService.GetById(id);
            returnUrl = returnUrl.Replace("%2F", "/");
            bool isValidAmount = false;
            if (food != null)
            {
                isValidAmount = _shoppingCart.AddToCart(food, amount.Value);
            }

            return Index(isValidAmount, returnUrl);
        }

        public IActionResult Remove(int foodId)
        {
            var food = _foodService.GetById(foodId);
            if (food != null)
            {
                _shoppingCart.RemoveFromCart(food);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Back(string returnUrl="/")
        {
            return Redirect(returnUrl);
        }
    }
}

Shop.Web/Views/Shared/FoodSummary.cshtml
@model Shop.Web.Models.Food.FoodListingModel

<div class="btn-addToCart">
    <div class="categoryPrice"> <input readonly class="form-control" style="outline:none" id="foodTotal-@(Model.GetHashCode())" value="@Model.Total"></div>
    @if(User.IsInRole("Admin"))
    {
        <div class="categoryPrice">In Stock: @Model.InStock</div>
    } 
    <form asp-controller="ShoppingCart" asp-action="Add"  method="get" class="form-horizontal" role="form">
        <a onclick="changeValue(document.getElementById('amount-input-'+@Model.Id.ToString()), document.getElementById('foodTotal-@(Model.GetHashCode())'),'@Model.Total', 1)"><i class="fas fa-plus-circle"></i></a>
        <input id="amount-input-@Model.Id" asp-for="Amount" style="width:20%" type="text" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
        <a onclick="changeValue(document.getElementById('amount-input-'+@Model.Id.ToString()),document.getElementById('foodTotal-@(Model.GetHashCode())'), '@Model.Total', -1)"><i class="fas fa-minus-circle"></i></a>
        <div class="btn-cart">
            <input value="Add to cart" type="submit" class="btn btn-success" asp-controller="ShoppingCart" asp-action="Add" asp-route-id="@Model.Id" asp-route-amount="@Model.Amount"  asp-route-returnUrl="@Context.Request.Path">
        </div>
    </form>
</div>

<div class="foodData">
    <div class="foodName">
        <div class="categoryLogo" style="background-image: url(@Model.ImageUrl);"></div>
        <a class="btn btn-info" asp-controller="Food" asp-action="Index" asp-route-id="@Model.Id">
            @Model.Name
        </a>
    </div>
</div>

Shop.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Shop.Data.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewBag.BodyClass = "bg1";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BuyNow - Online food store</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" /> 
    <environment include="Development">
        <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" /> -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body class="@ViewBag.BodyClass d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #f8f8f8;">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">
            <img src="/images/logo.png" width="140px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Category" asp-action="Index">Categories</a>
            </li>
            @if(User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Index">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Food" asp-action="New">New Food</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Category" asp-action="New">New Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Register">New User</a>
                </li>
            }
        </ul>
        <form class="form-inline">
            @if(SignInManager.IsSignedIn(User))
            {
                @await Component.InvokeAsync("ShoppingCartSummary")
                @await Component.InvokeAsync("AccountSummary")
            }
            else
            {
                @await Html.PartialAsync("_LoginPartial")
            }
        </form>
        </div>
    </nav>
    <div class="container body-content flex-shrink-0">
        @RenderBody()
    </div>
<!-- Footer -->
    <footer id="myFooter" class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <a style="width: 100%;height: 150px;margin-top: 0px;"  asp-controller="Home" asp-action="Index" class="navbar-brand navLogo footerLogo"></a>
                </div>
                <div class="col-sm-2">
                    <h5>Get started</h5>
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                        @if(SignInManager.IsSignedIn(User))
                        {
                                <li><a class="btn-link" asp-controller="Account" asp-action="Logout">Log out</a></li>
                        }
                        else
                        {
                            <li><a asp-action="Login" asp-controller="Account">Sign in</a></li>
                            <li><a asp-action="Register" asp-controller="Account">Sign up</a></li>
                        }
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <div class="social-networks">
                        <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fab fa-facebook"></i></a>
                        <a href="#" class="google"><i class="fab fa-google-plus"></i></a>
                    </div>
                    <button type="button" class="btn btn-default">Contact us</button>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>©2020 - BuyNow </p>
        </div>
    </footer>

    <environment include="Development">
        <!-- <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script> -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
     <script type="text/javascript">
         function changeValue(target, output,total,  num) {
             let val = parseInt(target.value);
             if (num < 0 && val <= 1) {
                 return;
             }
             val += num;
             target.value = val;

             let totalInt = val * parseFloat(total.substring(1));
             output.value = ('$' + totalInt).substring(0,6);
            }

        function readUrl(input, id) {  
            if (input && input.value) {
                $('#'+id).attr('src', input.value);
            }
        }    
     </script>

    @RenderSection("Scripts", required: false)
</body>